name: update tc Link
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install Selenium and Chrome
        run: |
          pip install requests selenium webdriver-manager
          
      - name: Run update script
        run: python update_tc.py
        
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add canales.json
          git commit -m "Update TC link via Selenium" || echo "No hay cambios"
          git push
